name: Update gist
on:
  repository_dispatch:
    types: [build-event]
#  schedule:
#    - cron: "0 0 * * *"
  workflow_dispatch:
  
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update gist
        uses: TunaHG/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: db19b828f15e82d7584c2a4ecbc0792f
          TIMEZONE: Asia/Seoul
